#!/usr/bin/env bash
usage(){
   cat <<- EOF
usage: dependency-diff [OPTIONS] <jar1> <jar2>
	EOF
	exit
}
if [ -z "$@" ];then
   usage
fi

args=()
unset jar1
unset jar2

for jar in $@;do
   j=${jar::1}
   if [ $j = '-' ];then
     args=(" $jar")
   else
     if [ ! $jar1 ];then
        jar1=$jar
        args+=($jar1)
     elif [ $jar1 -a ! $jar2 ];then
        jar2=$jar
        args+=($jar2)
     fi
   fi
done

getcli(){
  ARTIFACT_CLI='com.jfeat:dev-dependency:all'
  artifact_cli='dev-dependency-all.jar'
  artifact="/var/tmp/$artifact_cli"

  if [ ! -f $artifact_cli_path ];then 
    dependency-copy $ARTIFACT_CLI
    if [ ! -f $artifact_cli_path ];then 
      echo "fatal: dependency-copy $ARTIFACT_CLI failed !"
      exit
    fi
    mv $artifact_cli $artifact
  fi
}

artifact=$(getcli)
java -jar $artifact ${args[@]}
