#!/usr/bin/env bash
ARTIFACT='com.tools:dev-dependency:1.0:jar'
artifact='dev-dependency-1.0.jar'
artifact_ls="/var/tmp/$artifact"
artifact_cli='fatjar-find'

readdir(){
  bin=$1
  local dir=$(which $1)
        dir=${dir%/*}
  if [ -d $dir/node_modules/dev-cli ];then
     dir=$dir/node_modules/dev-cli
  fi
  if [[ $(uname -s) = Darwin ]];then
     dir=${dir%/*}/lib/node_modules/dev-cli
  fi
  echo $dir
}

getartifact(){
   if [ ! -d /var/tmp ];then
      mkdir -p /var/tmp
   fi   
   if [ ! -f $artifact_ls ];then
      mvn org.apache.maven.plugins:maven-dependency-plugin:3.2.0:copy -Dartifact=$ARTIFACT -DoutputDirectory=/var/tmp
   fi
   if [ ! -f $artifact_ls ];then
      local dir="$(readdir $artifact_cli)"

      echo fail to mvn copy $ARTIFACT > /dev/stderr
      echo "1> cp $dir/lib/$artifact ./$artifact_ls" > /dev/stderr
      cp $dir/lib/$artifact ./$artifact_ls
   fi
}

if [ ! -f $artifact_ls ];then
   getartifact
fi


## main
usage(){
   echo 'fatjar-diff [OPTIONS] <fatjar> <fatjar2>'
   echo ''
   echo 'OPTIONS: '
   echo '   -c --checksum        --output with checksum'
   exit 1
}

fatjar_opt=
fatjar2_opt=
checksum_opt=
for opt in $@;do
   if [[ $opt = '-c' || $opt = '--checksum' ]];then
      checksum_opt=$opt 
   elif [ $fatjar_opt ];then 
      fatjar2_opt=$opt
   else 
      fatjar_opt=$opt
   fi
done

if [ ! $fatjar2_opt ];then 
   usage
fi

# echo java -jar $artifact_ls -d $fatjar_opt $fatjar2_opt $checksum_opt
java -jar $artifact_ls -d $fatjar_opt $fatjar2_opt $checksum_opt


# ## check
# args=()
# unset jar1
# unset jar2
# for jar in $@;do
#    j=${jar::1}
#    if [ $j = '-' ];then
#      args=(" $jar")
#    else
#      if [ ! $jar1 ];then
#         jar1=$working_dir/$jar
#         args+=($jar1)
#       #   args=("${args[@]}" $jar1)
#      elif [ $jar1 -a ! $jar2 ];then
#         jar2=$working_dir/$jar
#         args+=($jar2)
#      fi
#    fi
# done

# dir=$(dirname $(realpath $0))
# if [ ! $dir ];then 
#   dir='.'
# fi
# java -jar $dir/local/lib/jar-dependency.jar ${args[@]}
