#!/bin/sh

usage(){
    echo 'usage: md5sum <target>'
    exit
}

target=$1
if [ ! $target ];then
   usage
fi
if [ ! -f $target ];then 
   echo $target not type of file !
   usage
fi

checksum -md5 -f $target
