#!/usr/bin/env bash
ARTIFACT='com.tools:pdf-page:1.0:jar:all'
artifact='pdf-page-1.0-all.jar'
artifact_ls="/var/tmp/$artifact"
artifact_cli='pdf-page'

getartifact(){
   if [ ! -d /var/tmp ];then
      mkdir -p /var/tmp
   fi 
   if [ ! -f $artifact_ls ];then
      mvn org.apache.maven.plugins:maven-dependency-plugin:3.2.0:copy -Dartifact=$ARTIFACT -DoutputDirectory=/var/tmp
   fi
   if [ ! -f $artifact_ls ];then
      local dir="$(dirname $(which $artifact_cli))/node_modules/dev-cli"

      echo fail to mvn copy $ARTIFACT > /dev/stderr
      echo "1> cp $dir/lib/$artifact ./$artifact_ls" > /dev/stderr
      cp $dir/lib/$artifact ./$artifact_ls
   fi
}

if [ ! -f $artifact_ls ];then
   getartifact
fi

## run jar 
java -jar $artifact_ls $@
