#!/bin/sh

usage(){
    echo 'usage: sha256sum <target>'
    exit
}

target=$1
if [ ! $target ];then
   usage
fi
if [ ! -f $target ];then 
   echo $target not type of file !
   usage
fi

checksum --sha256 -f $target
